#!/usr/bin/env bash
#
# First-run setup on a fresh Linux host. Installs Docker if needed, writes the
# environment, generates secrets, deploys, and seeds the demo catalogue.
#
#     ./scripts/bootstrap.sh <public-host> [web-port] [admin-port] [api-port]
#
# <public-host> is the IP or domain you will open in a browser. Everything else
# has a sane default:
#
#     ./scripts/bootstrap.sh 203.0.113.10
#     ./scripts/bootstrap.sh tours.example.com 8080 8081 8082
#
# Safe to re-run: it will not overwrite an existing .env.production, and the
# seed only fires on an empty catalogue.
set -Eeuo pipefail

readonly HOST="${1:-}"
readonly WEB_PORT="${2:-3000}"
readonly ADMIN_PORT="${3:-3001}"
readonly API_PORT="${4:-4000}"
readonly ENV_FILE=".env.production"

log() { printf '\033[1;33m▶ %s\033[0m\n' "$*"; }
ok()  { printf '\033[1;32m✔ %s\033[0m\n' "$*"; }
die() { printf '\033[1;31m✖ %s\033[0m\n' "$*" >&2; exit 1; }

[[ -n "$HOST" ]] || die "Usage: ./scripts/bootstrap.sh <public-host> [web-port] [admin-port] [api-port]"
[[ -f docker/docker-compose.prod.yml ]] || die "Run this from the repository root."

# --- docker --------------------------------------------------------------------

if ! command -v docker >/dev/null; then
  log "Installing Docker"
  curl -fsSL https://get.docker.com | sh
  ok "Docker installed"
fi

docker compose version >/dev/null 2>&1 || die "The Docker Compose plugin is missing."

# --- environment ---------------------------------------------------------------

if [[ -f "$ENV_FILE" ]]; then
  ok "$ENV_FILE already exists; leaving it alone"
else
  log "Writing $ENV_FILE for http://$HOST"

  secret() { openssl rand -base64 48 | tr -d '\n/+=' | cut -c1-48; }

  cat > "$ENV_FILE" <<ENV
# Generated by scripts/bootstrap.sh. Secrets are real; keep this file private.
POSTGRES_USER=pasta
POSTGRES_PASSWORD=$(secret)
POSTGRES_DB=pasta_roma_tour

JWT_ACCESS_SECRET=$(secret)
JWT_REFRESH_SECRET=$(secret)
JWT_ACCESS_TTL=15m
JWT_REFRESH_TTL=30d

SITE_URL=http://${HOST}:${WEB_PORT}
ADMIN_URL=http://${HOST}:${ADMIN_PORT}
PUBLIC_API_URL=http://${HOST}:${API_PORT}/api/v1
CORS_ORIGINS=http://${HOST}:${WEB_PORT},http://${HOST}:${ADMIN_PORT}

# Published on every interface so the app is reachable by IP without a proxy.
# Put nginx in front and set this back to 127.0.0.1 before going live.
BIND_HOST=0.0.0.0
WEB_PORT=${WEB_PORT}
ADMIN_PORT=${ADMIN_PORT}
API_PORT=${API_PORT}

STRIPE_SECRET_KEY=
STRIPE_PUBLISHABLE_KEY=
STRIPE_WEBHOOK_SECRET=

SMTP_URL=
MAIL_FROM=Pasta Roma Tour <no-reply@${HOST}>

SWAGGER_ENABLED=true
THROTTLE_TTL_SECONDS=60
THROTTLE_LIMIT=120
ENV

  chmod 600 "$ENV_FILE"
  ok "Secrets generated (file is chmod 600)"
fi

# --- firewall ------------------------------------------------------------------

if command -v ufw >/dev/null && ufw status 2>/dev/null | grep -q "Status: active"; then
  log "Opening ports in ufw"
  ufw allow "$WEB_PORT/tcp"   >/dev/null || true
  ufw allow "$ADMIN_PORT/tcp" >/dev/null || true
  ufw allow "$API_PORT/tcp"   >/dev/null || true
fi

# --- deploy --------------------------------------------------------------------

./scripts/deploy.sh --seed

cat <<DONE

  ────────────────────────────────────────────────────────────
   Landing page   http://${HOST}:${WEB_PORT}
   Admin / CRM    http://${HOST}:${ADMIN_PORT}
   API docs       http://${HOST}:${API_PORT}/api/v1/docs

   CRM login      admin@pastaromatour.com
                  ChangeMe123!   ← change this now
  ────────────────────────────────────────────────────────────

  This serves plain HTTP with no TLS. Fine for a first look; put nginx
  and a certificate in front before real traffic — docs/SERVER-SETUP.md §6.

DONE
